### ISSUE TITLE
Motors_Sync issue

### ISSUE THREAD

**Issue by YanceyA** [MRX8024/Voron_mods#1]
@MRX8024  Hey, sorry to post this in the wrong place but the motor_sync doesn't have issue tracking open. I got everything setup but everytime i run motors sync I get what looks like a python error during the process:

_7 cputime=11.280 memavail=3689296 print_time=86.238 buffer_time=0.000 print_stall=0 extruder: target=0 temp=13.3 pwm=0.000
Writing raw accelerometer data to /tmp/beacon-20240504_213802.csv file
Y-New magnitude: None on -1/16 step move
Internal error on command:"SYNC_MOTORS"
Traceback (most recent call last):
  File "/home/yanceya/klipper/klippy/gcode.py", line 298, in _process_commands
    handler(gcmd)
  File "/home/yanceya/klipper/klippy/gcode.py", line 207, in func
    return origfunc(self._get_extended_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanceya/klipper/klippy/extras/motors_sync.py", line 266, in cmd_RUN_SYNC
    self._axes_level()
  File "/home/yanceya/klipper/klippy/extras/motors_sync.py", line 155, in _axes_level
    if m['new_magnitude'] > m['magnitude']:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'NoneType'
Transition to shutdown state: Internal error on command:"SYNC_MOTORS"_

I've attached the relevant klippy log:
[klippy_motors_sync_error.txt](https://github.com/MRX8024/Voron_mods/files/15211225/klippy_motors_sync_error.txt)

I'm running a monolith AWD and Beacon as the accelerometer sensor.

**Comment by MRX8024** [comment]
Hello!  I've added an issue tab, thanks. Regarding your problem, try increasing CSV_OPEN_DELAY in 12 line .py file to for example 0.5 (sec), other reasons are still unclear to me. If this doesn’t help, open an issue in the original repository, its more correct.

-Maxim

**Comment by YanceyA** [comment]
Issue opened in correct project and closed here.

**Comment by YanceyA** [comment]
Issue opened in correct project and closed here.
